### ISSUE TITLE
複数のSkinnedMeshRendererで一つのモジュールとして生成したい

### ISSUE THREAD

**Issue by anatawa12** [Tliks/ModuleCreator#63]
タイトルのとおりです。素体の服が複数のSMRに別れてる場合一つにしたいです。

例:みずきちゃんのベルトと服が別れてるが一つのモジュールでも適当

**Comment by Tliks** [comment]
devブランチに現在実装してあるCreate Module (Advanced)内のCombine Prefabが該当する機能だと思います。次期リリースに含まれる予定です
